apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-fastapi
  namespace: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      version: fastapi
  template:
    metadata:
      labels:
        app: my-app
        version: fastapi
    spec:
      containers:
      - name: my-app
        image: jmpinillag/count-fastapi-redis:latest
        ports:
        - containerPort: 5002
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: configmap-fastapi
